# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH connection with password
        run: |
          env
          echo "Installing sshpass..."
          sudo apt-get install -y sshpass

          echo "Connecting to the server..."
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no username@${{ secrets.HOST }} << EOF
          echo "Successfully connected to the server!"
          sudo apt-get update -y
          echo "Server packages updated successfully!"
          EOF

      - name: Deploy to server
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} <<'ENDSSH'
          cd ${{ secrets.APP_PATH }}
          git pull
          npm i --force
          npm run prod
          ENDSSH
        